/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from "./routes/__root";
import { Route as IndexImport } from "./routes/index";
import { Route as WorkDetailsWorkIdImport } from "./routes/work-details/$workId";

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRoute,
} as any);

const WorkDetailsWorkIdRoute = WorkDetailsWorkIdImport.update({
  id: "/work-details/$workId",
  path: "/work-details/$workId",
  getParentRoute: () => rootRoute,
} as any);

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexImport;
      parentRoute: typeof rootRoute;
    };
    "/work-details/$workId": {
      id: "/work-details/$workId";
      path: "/work-details/$workId";
      fullPath: "/work-details/$workId";
      preLoaderRoute: typeof WorkDetailsWorkIdImport;
      parentRoute: typeof rootRoute;
    };
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/work-details/$workId": typeof WorkDetailsWorkIdRoute;
}

export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/work-details/$workId": typeof WorkDetailsWorkIdRoute;
}

export interface FileRoutesById {
  __root__: typeof rootRoute;
  "/": typeof IndexRoute;
  "/work-details/$workId": typeof WorkDetailsWorkIdRoute;
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/" | "/work-details/$workId";
  fileRoutesByTo: FileRoutesByTo;
  to: "/" | "/work-details/$workId";
  id: "__root__" | "/" | "/work-details/$workId";
  fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  WorkDetailsWorkIdRoute: typeof WorkDetailsWorkIdRoute;
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WorkDetailsWorkIdRoute: WorkDetailsWorkIdRoute,
};

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/work-details/$workId"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/work-details/$workId": {
      "filePath": "work-details/$workId.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
